// Ambient types for the emscripten glue generated by `npm run wasm`.
// Keeps typecheck green whether or not client/sdk/gen exists yet.

declare module '*/gen/box2d.mjs' {
  const createBox2d: (options?: Record<string, unknown>) => Promise<unknown>;
  export default createBox2d;
}

declare module '*/gen/box3d.mjs' {
  const createBox3d: (options?: Record<string, unknown>) => Promise<unknown>;
  export default createBox3d;
}
